name: test

on:
  pull_request_review:

permissions:
  contents: write

jobs:
  timestamp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base ref
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Create current_time file
        run: echo "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" > current_time

      - name: Push current_time file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add current_time
          git commit -m "Update current_time"
          git push
